# Downsampling bam files that were merged (replicates merged), and generating bigwigs and macs2 peak-calling
## 22/02/2024 Jeanne 

configfile: "config.json"

WORKDIR = config["WORKING_PATH"]

rule all:
    input:
        # bigwigs
        bw_raw_allchr=expand(WORKDIR+"bigwig/raw/downsampled/{cell_type}_{target_mark}_downsampled.raw.bw", cell_type=config["CELL_TYPE"], target_mark=config["TARGET_MARK"]),
        bw_log2ratioigg_chrX=expand(WORKDIR+"bigwig/log2ratioigg/downsampled/{cell_type}_{target_mark}_downsampled.log2ratioigg.chrX.bw", cell_type=config["CELL_TYPE"], target_mark=config["TARGET_MARK"]),
        bw_log2ratioigg_allchr=expand(WORKDIR+"bigwig/log2ratioigg/downsampled/{cell_type}_{target_mark}_downsampled.log2ratioigg.bw", cell_type=config["CELL_TYPE"], target_mark=config["TARGET_MARK"]),
        # bam stats
        idxstats=expand(WORKDIR+"idxstats/{cell_type}_{target_mark}_downsampled.idxstats.txt", cell_type=config["CELL_TYPE"], target_mark=config["TARGET_MARK"]),
        # macs2 peaks enlarged
        enlarged_peaks=expand(WORKDIR+"macs2/{cell_type}_{target_mark}_macs2_enlarged.bed", cell_type=config["CELL_TYPE"], target_mark=config["TARGET_MARK"])




# DOWNSAMPLING

rule index_merged_PXGL:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/PXGL_{mark}_Filtered.merged.bam"
    output:
        bai=WORKDIR+"bam/merged_downsampled_bam/PXGL_{mark}_Filtered.merged.bam.bai"
    threads: 4
    singularity:
        "cutrun.sif"
    shell:
        """
        samtools index -@ {threads} {input.bam}
        """


rule index_merged_TSC_EXMC_primed:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/{sample}.hg38.dedupped.merged.bam",
    output:
        bai=WORKDIR+"bam/merged_downsampled_bam/{sample}.hg38.dedupped.merged.bam.bai"
    threads: 4
    singularity:
        "cutrun.sif"
    shell:
        """
        samtools index -@ {threads} {input.bam}
        """


rule bam_downsampling_PXGL:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/PXGL_{target_mark}_Filtered.merged.bam",
        bai=WORKDIR+"bam/merged_downsampled_bam/PXGL_{target_mark}_Filtered.merged.bam.bai"
    output:
        bam_downsampled=WORKDIR+"bam/merged_downsampled_bam/PXGL_{target_mark}_downsampled.bam"
    log:
        "log/PXGL_{target_mark}_downsampling.log"
    threads: 6
    singularity:
        "cutrun.sif"
    shell:
        """
        reads=26500000
        bam={input.bam}
        fraction=$(samtools idxstats -@ {threads} $bam | cut -f3 | awk -v ct=$reads 'BEGIN {{total=0}} {{total += $1}} END {{print ct/total}}')
        samtools view -@ {threads} -b -s ${{fraction}} $bam > {output.bam_downsampled} 2> {log}
        """


rule bam_downsampling_TSC_EXMC_primed:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}.hg38.dedupped.merged.bam",
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}.hg38.dedupped.merged.bam.bai"
    output:
        bam_downsampled=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam"
    log:
        "log/{cell_type}_{target_mark}_downsampling.log"
    threads: 6
    singularity:
        "cutrun.sif"
    shell:
        """
        reads=26500000
        bam={input.bam}
        fraction=$(samtools idxstats -@ {threads} $bam | cut -f3 | awk -v ct=$reads 'BEGIN {{total=0}} {{total += $1}} END {{print ct/total}}')
        samtools view -@ {threads} -b -s ${{fraction}} $bam > {output.bam_downsampled} 2> {log}
        """


rule index_downsampled_CUTRUN:
    input:
        WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam"
    output:
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam.bai"
    threads: 4
    singularity:
        "cutrun.sif"
    shell:
        """
        samtools index -@ {threads} {input}
        """


rule idxstats_bam:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam",
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam.bai"
    output: 
        WORKDIR+"idxstats/{cell_type}_{target_mark}_downsampled.idxstats.txt"
    log: 
        "log/{cell_type}_{target_mark}_downsampled.idxstats.err"
    singularity:
        "cutrun.sif"
    shell:
        """
        samtools idxstats {input.bam} > {output} 2> {log}
        """

# INDEXING IGG BAM
rule index_merged_igg:
    input:
        bam_merged=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_IGG.merged.bam"
    output:
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_IGG.merged.bam.bai"
    threads: 4
    singularity:
        "cutrun.sif"
    shell:
        """
        samtools index -@ {threads} {input.bam_merged}
        """

# BIGWIGs

# chrX only
rule bigwig_bpm_X:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam",
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam.bai"
    output: 
        WORKDIR+"bigwig/bpm/downsampled/{cell_type}_{target_mark}_downsampled.bpm.chrX.bw"
    params:
        normalization_method="BPM",
        binSize=20,
        smoothLength=40
    log: 
        "log/{cell_type}_{target_mark}_bpm-bw-chrX.log"
    singularity:
        "cutrun.sif"
    shell:
        """
        bamCoverage -b {input.bam} --normalizeUsing {params.normalization_method} --binSize {params.binSize} --smoothLength {params.smoothLength} --region chrX -o {output} 2> {log}
        """


rule bigwig_igg_bpm_X:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_IGG.merged.bam",
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_IGG.merged.bam.bai",
    output: 
        WORKDIR+"bigwig/bpm/downsampled/{cell_type}_IGG.merged.bpm.chrX.bw"
    params:
        normalization_method="BPM",
        binSize=20,
        smoothLength=40
    log: 
        "log/{cell_type}_IGG_bpm-bw-chrX.log"
    singularity:
        "cutrun.sif"
    shell:
        """
        bamCoverage -b {input.bam} --normalizeUsing {params.normalization_method} --binSize {params.binSize} --smoothLength {params.smoothLength} --region chrX -o {output} 2> {log}
        """


rule bw_igg_norm_chrX:
    input:
        target=WORKDIR+"bigwig/bpm/downsampled/{cell_type}_{target_mark}_downsampled.bpm.chrX.bw",
        igg=WORKDIR+"bigwig/bpm/downsampled/{cell_type}_IGG.merged.bpm.chrX.bw"
    output:
        bw_log2ratioigg=WORKDIR+"bigwig/log2ratioigg/downsampled/{cell_type}_{target_mark}_downsampled.log2ratioigg.chrX.bw"
    log:
        err="log/{cell_type}_{target_mark}_bw_downsampled_log2igg.err"
    singularity:
        "cutrun.sif"
    shell:
        """
        bigwigCompare -b1 {input.target} -b2 {input.igg} \\
        --operation log2 \\
        --outFileName {output.bw_log2ratioigg} \\
        --outFileFormat bigwig
        2> {log.err}
        """


# all chromosomes
rule bigwig_raw:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam",
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam.bai"
    output: 
        WORKDIR+"bigwig/raw/downsampled/{cell_type}_{target_mark}_downsampled.raw.bw"
    params:
        binSize=20,
        smoothLength=40
    log: 
        "log/{cell_type}_{target_mark}_raw-bw.log"
    singularity:
        "cutrun.sif"
    shell:
        """
        bamCoverage -b {input.bam} --binSize {params.binSize} --smoothLength {params.smoothLength} -o {output} 2> {log}
        """
    

rule bigwig_bpm:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam",
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam.bai"
    output: 
        WORKDIR+"bigwig/bpm/downsampled/{cell_type}_{target_mark}_downsampled.bpm.bw"
    params:
        normalization_method="BPM",
        binSize=20,
        smoothLength=40
    log: 
        "log/{cell_type}_{target_mark}_bpm-bw.log"
    singularity:
        "cutrun.sif"
    shell:
        """
        bamCoverage -b {input.bam} --normalizeUsing {params.normalization_method} --binSize {params.binSize} --smoothLength {params.smoothLength} -o {output} 2> {log}
        """


rule bigwig_igg_bpm:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_IGG.merged.bam",
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_IGG.merged.bam.bai"
    output: 
        WORKDIR+"bigwig/bpm/downsampled/{cell_type}_IGG.merged.bpm.bw"
    params:
        normalization_method="BPM",
        binSize=20,
        smoothLength=40
    log: 
        "log/{cell_type}_IGG_bpm-bw.log"
    singularity:
        "cutrun.sif"
    shell:
        """
        bamCoverage -b {input.bam} --normalizeUsing {params.normalization_method} --binSize {params.binSize} --smoothLength {params.smoothLength} -o {output} 2> {log}
        """


rule bw_igg_norm:
    input:
        target=WORKDIR+"bigwig/bpm/downsampled/{cell_type}_{target_mark}_downsampled.bpm.bw",
        igg=WORKDIR+"bigwig/bpm/downsampled/{cell_type}_IGG.merged.bpm.bw"
    output:
        bw_log2ratioigg=WORKDIR+"bigwig/log2ratioigg/downsampled/{cell_type}_{target_mark}_downsampled.log2ratioigg.bw"
    log:
        err="log/{cell_type}_{target_mark}_bw_downsampled_log2igg_allchr.err"
    singularity:
        "cutrun.sif"
    shell:
        """
        bigwigCompare -b1 {input.target} -b2 {input.igg} \\
        --operation log2 \\
        --outFileName {output.bw_log2ratioigg} \\
        --outFileFormat bigwig
        2> {log.err}
        """



# MACS2

rule macs2:
    input:
        bam=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam",
        bai=WORKDIR+"bam/merged_downsampled_bam/{cell_type}_{target_mark}_downsampled.bam.bai"
    output:
        peaks=WORKDIR+"macs2/{cell_type}_{target_mark}_macs2_peaks.broadPeak",
        gapped_peaks=WORKDIR+"macs2/{cell_type}_{target_mark}_macs2_peaks.gappedPeak",
        xls=WORKDIR+"macs2/{cell_type}_{target_mark}_macs2_peaks.xls"
    params:
        out_dir=WORKDIR+"macs2/",
        broad_cutoff=0.1
    log:
        "log/{cell_type}_{target_mark}_macs2.log"
    singularity:
        "cutrun.sif"
    shell:
        "(macs2 callpeak \
            -t {input.bam} \
            -f BAMPE \
            -g 2913022398 \
            -n {wildcards.cell_type}_{wildcards.target_mark}_macs2 \
            --outdir {params.out_dir} \
            --keep-dup 'all' \
            --broad \
            --broad-cutoff {params.broad_cutoff} \
            --nolambda) \
            2> {log}" 

#genome effecive size (-g) from deeptools : https://deeptools.readthedocs.io/en/develop/content/feature/effectiveGenomeSize.html 


rule enlarging_peaks:
    input:
        peaks=WORKDIR+"macs2/{cell_type}_{target_mark}_macs2_peaks.broadPeak"
    output:
        enlarged_peaks=WORKDIR+"macs2/{cell_type}_{target_mark}_macs2_enlarged.bed"
    params:
        distance=10000
    shell:
        """
        bedtools merge -i {input.peaks} -d {params.distance} > {output.enlarged_peaks}
        """


